apiVersion: v1
kind: Config
preferences: {}
clusters:
- name: default
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTnpneE5qZzJPRFF3SGhjTk1qWXdOVEEzTVRRME5EUTBXaGNOTXpZd05UQTBNVFEwTkRRMApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTnpneE5qZzJPRFF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFUWWkyN2tLWjFOTzgwSXl4aVpvRjRHdUwxckk4NDRpbVRTRW5sUjRFREQKVmxpWFNLSngwUnZlczhsd3RUdXQvbGZVcldrMmhCaFFISVppbVVXMVR4dEVvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVWFLZGFRdUlLVFgxMTRzTG51dVRyCkd0UUlPWE13Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnU3VaUTdiM2lIMlovRXB4Ukxjb3ZKajdXMXV1aVZ2NnYKaVVBQkJFQ1lWYWNDSUdnZ05Za2lMMkxaaW03YXVPVDliWEhJd0R3SE5BVlBVV1c0aytEbUQ3OVkKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://193.136.82.35:6443
contexts:
- name: tenant-grupo7-egs-deti-ua-pt-context
  context:
    cluster: default
    namespace: tenant-grupo7-egs-deti-ua-pt
    user: tenant-sa
current-context: tenant-grupo7-egs-deti-ua-pt-context
users:
- name: tenant-sa
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkZwU3BaWEdYa2lpODk5aXFYbEE5S2dIZGszYTJqYUtoeFhnejBfQUh3ZVEifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJrM3MiXSwiZXhwIjoxNzkzNzc5MzEyLCJpYXQiOjE3NzgyMjczMTIsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiYmYyYTFhYmEtNzM0ZS00NzFmLThjNzEtYjZlZDE0MGUwNjJmIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJ0ZW5hbnQtZ3J1cG83LWVncy1kZXRpLXVhLXB0Iiwic2VydmljZWFjY291bnQiOnsibmFtZSI6InRlbmFudC1zYSIsInVpZCI6ImI3YTg5ZjBkLThlYzMtNDUzYi1hNjJmLTUwZmQ4Y2NlNTc4YSJ9fSwibmJmIjoxNzc4MjI3MzEyLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6dGVuYW50LWdydXBvNy1lZ3MtZGV0aS11YS1wdDp0ZW5hbnQtc2EifQ.bu8uRA1yF29cdmB8nzNVUSIxfn8mZVhSj2wp4siAbBMPa1WwGCXdCMde2o4GzPW4pLXDX84zIN8nLe9yrxjN01y6Ts6RZpVouUEIj01N_IX0eRVv8lp3noLc2CjNfPsIBhNvkfUoTqJRfqV-WPUCyn_iJsUtTUSTJiudPLZtyOh7yL3CT1QQiKbOJTjcn5dUIFf88KAhaJ3rOnl6Pxm86KVttUfBCd5MTPIUci-RkFAHGxwm5BOheVsvpHisj0fpiHld7nri5p7SkgIMIFDA6y7FUQaj4eKUErHefrdHiitkkATf3Rl6OW0tGMUDVgk-DaFALzgTVPDuIIMAdD8DzA
