apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: stormos
      defaultBucket: stormos
      tlsSkipVerify: true
    secureJsonData:
      token: stormos-super-secret-token
    isDefault: true
    editable: true
