services:
  db:
    image: postgis/postgis:15-3.3 # Imagem oficial com PostGIS
    container_name: postgis_db
    environment:
      POSTGRES_USER: user_geo
      POSTGRES_PASSWORD: password_geo
      POSTGRES_DB: geodb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Carrega o seu SQL automaticamente